print("esta es mi prueba")
print("Hola mundo")


#hola esta es otra prueba
print("Cruel")

print("            ___")
print("        ,-""   `-.              ")
print("      ,'         `.           ")
print("     /             \\          ")
print("    /               \\        ")
print("   /                 \\     ")
print("  /_   ___ __ _ _ __|_        ")
print("  \\ `-' / _` | '__| `\\     ")
print("   `._.`\__,_|_|  |_,'    ")
print("         |           ")
print("        / \\         ")
print("       /   \\        ")
print("      /     \\       ")
print("     /       \\      ")
print("    /         \\     ")
print("   /           \\    ")
print("  /             \\   ")
print(" /               \\  ")
print("/_________________\\ ")
